#ifndef D_MK24F12_SYS_PITMGR_PORT_H
#define D_MK24F12_SYS_PITMGR_PORT_H

#include "cmodule_common.h"

#if defined(CMODULE_USE_PITMGR) && (CMODULE_USE_PITMGR > 0)

#define CMODULE_PITMGR_DEFAULT_IRQ 	(1U)

#endif // ! CMODULE_USE_PITMGR

#endif // ! D_MK24F12_SYS_PITMGR_PORT_H
